# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
