# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 01:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 14, 1, 38, 24, 581716, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 14, 1, 38, 30, 303605, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
